# GoReleaser configuration for Claude Plan Orchestrator
# Run: goreleaser release --clean
# Or for testing: goreleaser build --snapshot --clean

version: 2

project_name: claude-orch

before:
  hooks:
    - go mod tidy

builds:
  - id: claude-orch
    main: ./cmd/claude-orch
    binary: claude-orch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: unix
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    builds:
      - claude-orch
    files:
      - README.md
      - LICENSE*
      - scripts/onboard.sh
    rlcp: true
    filter:
      include:
        - goos: linux
        - goos: darwin

  - id: windows
    formats:
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    builds:
      - claude-orch
    files:
      - README.md
      - LICENSE*
      - scripts/onboard.sh
    rlcp: true
    filter:
      include:
        - goos: windows

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: hochfrequenz
    name: claude-plan-orchestrator
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
