#!/usr/bin/env bash
#
# Claude Plan Orchestrator Project Onboarding
# Interactive setup for using claude-orch with a new project
#
# Usage:
#   claude-orch-onboard
#   # or
#   ./scripts/onboard.sh
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info() { echo -e "${BLUE}==>${NC} $1"; }
success() { echo -e "${GREEN}==>${NC} $1"; }
warn() { echo -e "${YELLOW}==>${NC} $1"; }
error() { echo -e "${RED}Error:${NC} $1" >&2; }
header() { echo -e "\n${BOLD}${CYAN}$1${NC}\n"; }

# Default paths
CONFIG_DIR="${HOME}/.config/claude-orchestrator"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
DATA_DIR="${HOME}/.claude-orchestrator"

# Prompt for input with default
prompt() {
    local message="$1"
    local default="$2"
    local result

    echo -en "${BLUE}?${NC} ${message} "
    if [[ -n "$default" ]]; then
        echo -en "[${default}] "
    fi
    read -r result
    echo "${result:-$default}"
}

# Yes/no prompt
confirm() {
    local message="$1"
    local default="${2:-y}"
    local result

    if [[ "$default" == "y" ]]; then
        echo -en "${BLUE}?${NC} ${message} [Y/n] "
    else
        echo -en "${BLUE}?${NC} ${message} [y/N] "
    fi
    read -r result
    result="${result:-$default}"
    [[ "$result" =~ ^[Yy] ]]
}

# Check prerequisites
check_prerequisites() {
    header "Checking Prerequisites"

    local missing=()

    # Git
    if command -v git &> /dev/null; then
        success "Git: $(git --version | head -1)"
    else
        missing+=("git")
        error "Git not found"
    fi

    # Claude CLI
    if command -v claude &> /dev/null; then
        success "Claude CLI: found"
    else
        missing+=("claude")
        warn "Claude CLI not found (required for agent execution)"
    fi

    # claude-orch
    if command -v claude-orch &> /dev/null; then
        success "claude-orch: $(claude-orch --version 2>/dev/null || echo 'found')"
    else
        warn "claude-orch not in PATH (using local if available)"
    fi

    if [[ ${#missing[@]} -gt 0 ]]; then
        echo ""
        warn "Missing prerequisites: ${missing[*]}"
        if ! confirm "Continue anyway?"; then
            exit 1
        fi
    fi
}

# Get project information
get_project_info() {
    header "Project Configuration"

    # Project root
    local default_root
    if [[ -d ".git" ]]; then
        default_root="$(pwd)"
    else
        default_root=""
    fi

    PROJECT_ROOT=$(prompt "Project root directory" "$default_root")
    PROJECT_ROOT="${PROJECT_ROOT/#\~/$HOME}"  # Expand ~

    if [[ ! -d "$PROJECT_ROOT" ]]; then
        error "Directory does not exist: $PROJECT_ROOT"
        exit 1
    fi

    if [[ ! -d "$PROJECT_ROOT/.git" ]]; then
        warn "Not a git repository: $PROJECT_ROOT"
        if ! confirm "Continue anyway?"; then
            exit 1
        fi
    fi

    # Project name (for display)
    PROJECT_NAME=$(prompt "Project name" "$(basename "$PROJECT_ROOT")")

    # Max parallel agents
    MAX_AGENTS=$(prompt "Max parallel agents" "3")

    # Worktree directory
    WORKTREE_DIR=$(prompt "Worktree directory" "${DATA_DIR}/worktrees/${PROJECT_NAME}")

    # Database path
    DB_PATH=$(prompt "Database path" "${DATA_DIR}/${PROJECT_NAME}.db")
}

# Configure notifications
configure_notifications() {
    header "Notifications"

    DESKTOP_NOTIFY="true"
    if ! confirm "Enable desktop notifications?" "y"; then
        DESKTOP_NOTIFY="false"
    fi

    SLACK_WEBHOOK=""
    if confirm "Configure Slack notifications?" "n"; then
        SLACK_WEBHOOK=$(prompt "Slack webhook URL" "")
    fi
}

# Configure web UI
configure_web() {
    header "Web UI"

    WEB_PORT=$(prompt "Web UI port" "8080")
    WEB_HOST=$(prompt "Web UI host" "127.0.0.1")
}

# Create config file
create_config() {
    header "Creating Configuration"

    mkdir -p "$CONFIG_DIR"
    mkdir -p "$(dirname "$DB_PATH")"
    mkdir -p "$WORKTREE_DIR"

    cat > "$CONFIG_FILE" << EOF
# Claude Plan Orchestrator Configuration
# Generated by onboard script on $(date)

[general]
# Path to the project repository
project_root = "${PROJECT_ROOT}"

# Directory for agent worktrees
worktree_dir = "${WORKTREE_DIR}"

# Maximum concurrent agents
max_parallel_agents = ${MAX_AGENTS}

# SQLite database path
database_path = "${DB_PATH}"

[claude]
# Claude model to use
model = "claude-opus-4-5-20251101"

# Max tokens per response
max_tokens = 16000

[notifications]
# Enable desktop notifications
desktop = ${DESKTOP_NOTIFY}

# Slack webhook URL (optional)
slack_webhook = "${SLACK_WEBHOOK}"

[web]
# Web UI host
host = "${WEB_HOST}"

# Web UI port
port = ${WEB_PORT}
EOF

    success "Created config: $CONFIG_FILE"
}

# Create plans directory structure
create_plans_structure() {
    header "Setting Up Plans Directory"

    local plans_dir="${PROJECT_ROOT}/docs/plans"

    if [[ -d "$plans_dir" ]]; then
        info "Plans directory already exists: $plans_dir"
    else
        if confirm "Create plans directory at ${plans_dir}?" "y"; then
            mkdir -p "$plans_dir"
            success "Created: $plans_dir"
        fi
    fi

    # Create sample plan
    if confirm "Create a sample plan file?" "y"; then
        local sample_file="${plans_dir}/sample-module/epic-00-setup.md"
        mkdir -p "$(dirname "$sample_file")"

        cat > "$sample_file" << 'EOF'
---
module: sample
epic: 0
title: Project Setup
priority: high
---

# Epic 00: Project Setup

Initial project scaffolding and configuration.

## Description

This epic covers the basic setup tasks needed before development can begin.

## Acceptance Criteria

- [ ] Development environment configured
- [ ] Dependencies installed
- [ ] CI/CD pipeline set up
- [ ] Documentation structure created

## Tasks

1. Set up development environment
2. Install project dependencies
3. Configure linting and formatting
4. Create initial documentation

## Notes

This is a sample epic file. Modify or replace with your actual project plans.
EOF

        success "Created sample plan: $sample_file"
    fi

    # Create README in plans directory
    local readme="${plans_dir}/README.md"
    if [[ ! -f "$readme" ]]; then
        cat > "$readme" << 'EOF'
# Development Plans

This directory contains implementation plans organized by module.

## Structure

```
plans/
├── {module-name}/
│   ├── epic-00-setup.md
│   ├── epic-01-core.md
│   └── ...
└── README.md
```

## Status Legend

- 🔴 Not started
- 🟡 In progress
- 🟢 Complete

## Task Format

Each epic file uses YAML frontmatter:

```yaml
---
module: module-name
epic: 1
title: Epic Title
priority: high|normal|low
depends_on:
  - other-module/E00
---
```

## Commands

```bash
# Sync tasks from plans
claude-orch sync

# View status
claude-orch status

# Start tasks
claude-orch start
```
EOF

        success "Created: $readme"
    fi
}

# Initial sync
initial_sync() {
    header "Initial Sync"

    if confirm "Run initial task sync?" "y"; then
        if command -v claude-orch &> /dev/null; then
            claude-orch sync
            success "Tasks synced successfully"
        else
            warn "claude-orch not in PATH, skipping sync"
            echo "Run 'claude-orch sync' manually after adding to PATH"
        fi
    fi
}

# Print summary
print_summary() {
    header "Setup Complete!"

    echo "Configuration:"
    echo "  Config file:    $CONFIG_FILE"
    echo "  Project root:   $PROJECT_ROOT"
    echo "  Worktree dir:   $WORKTREE_DIR"
    echo "  Database:       $DB_PATH"
    echo ""
    echo "Next steps:"
    echo ""
    echo "  1. Create your implementation plans in:"
    echo "     ${PROJECT_ROOT}/docs/plans/{module}/epic-XX-name.md"
    echo ""
    echo "  2. Sync tasks:"
    echo "     claude-orch sync"
    echo ""
    echo "  3. Start the orchestrator:"
    echo "     claude-orch start              # Start ready tasks"
    echo "     claude-orch tui                # TUI dashboard"
    echo "     claude-orch serve              # Web UI at http://${WEB_HOST}:${WEB_PORT}"
    echo ""
    echo "  4. Monitor progress:"
    echo "     claude-orch status             # Quick summary"
    echo "     claude-orch list               # All tasks"
    echo ""

    success "Happy orchestrating!"
}

# Main
main() {
    echo ""
    echo "  ╔═══════════════════════════════════════╗"
    echo "  ║   Claude Plan Orchestrator Project Onboarding  ║"
    echo "  ╚═══════════════════════════════════════╝"
    echo ""

    check_prerequisites
    get_project_info
    configure_notifications
    configure_web
    create_config
    create_plans_structure
    initial_sync
    print_summary
}

main "$@"
